name: Deploy KungFu Taishan Backend

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-example
          path: ${{ github.workspace }}/target/*.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: springboot-example
      - name: Deploy to Azure App Services
        uses: azure/webapps-deploy@v2
        with:
          app-name: kungfutaishan
          publish-profile: ${{ secrets.azureWebAppPublicProfile }}
          package: '*.jar'
          startup-command: 'java -jar -Dspring.profiles.active=prod *.jar'
